### ISSUE TITLE
Launch on GPU without cudnn?

### ISSUE THREAD

**Issue by LeonArcher** [yusuketomoto/chainer-fast-neuralstyle#38]
Hi! Has anyone tried to run the algorithm on GPU without cudnn? I have Tesla C2075 (it doesn't support cudnn due to level 2.0 CUDA compute capability) and Windows Server 2012 (Python 2.7 x64). I was able to install Chainer smoothly (both with cudnn and without), but without cudnn I got the following error: "CUDA_ERROR_INVALID_VALUE: invalid argument", when "im2col_gpu" is called.

Everything works perfectly with cudnn support (tested on GTX 760), but I really would like to use Tesla somehow due to the much greater performance...

**Comment by DylanAlloy** [comment]
Using a GPU without CUDNN kind of defeats the purpose of using a Nvidia GPU to train neural networks. The reason the Tesla is better is because it has more CUDA cores and memory. If you're not using the CUDA cores, all you have is slow memory. Not very appealing.

**Comment by tisawe** [comment]
Using a CUDA capable GPU is still faster than using a CPU, even without cuDNN. That makes this appealing to anyone who would like to expirament or anytime without the hardware or money.

**Comment by DylanAlloy** [comment]
I would think the biggest advantage with the Tesla card is loads more VRAM but for training that isn't as crucial. 

And to be honest I don't know for sure that a card with more cores and a faster clock speed is really better than a older mid-range card that has CUDnn capability. The enhancements made by the library to manipulate primitive datatypes is very significant, which is why people like to use it on Nvidia cards.

My suggestion would be to look at the arithmetic with the matrix algebra in the algorithm and see if you can revert it back to something nonreliant on CUDnn but still using CUDA. Perhaps using PyCuda exclusively.

**Comment by LeonArcher** [comment]
Well, actually the algorithm runs good on GTX760 even without CUDNN support - I've tried the library compiled without CUDNN (but it consumes twice as much video memory on same images). I've done some more research (different drivers, WDDM/TCC modes, different CUDA versions), but was unable to solve the problem on Tesla.

Thank you for your advices anyway!
